/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.fiap.dashboard;

import br.fiap.dao.DashboardDAO;
import br.fiap.model.Aluno;
import br.fiap.model.Foguete;
import br.fiap.model.Grupo;
import br.fiap.model.Lancamento;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paesv
 */
public class PainelGrupoForm extends javax.swing.JFrame {
     
    DashboardDAO dao = new DashboardDAO();

    /** Creates new form PainelGrupoForm */
    public PainelGrupoForm() {
        initComponents();
    }
    
    public void preencherTabela(int id_grupo){
        DefaultTableModel modelo = (DefaultTableModel) tableMembros.getModel();
        
        DashboardDAO dao = new DashboardDAO();
        
        //String nomeGrupo = lblNomeGrupo.getText();
        
        for(Aluno a:dao.preencherTabela(id_grupo)){
            
            modelo.addRow(new Object[]{
                a.getNome(),
                a.getRm()
            });
            
        }
    }
    
    public void preencherPainel(Grupo grupo){
        String nomeGrupo = grupo.getNome();
        
        lblNomeGrupo.setText(grupo.getNome());
        lblTurma.setText(grupo.getTurma());
        
        preencherTabela(id_grupo);
        preencherFoguete();
    }
    
    public void preencherFoguete(){
        Foguete foguete = new Foguete();
        String nomeGrupo = lblNomeGrupo.getText();
       
        if(dao.checarFoguete(nomeGrupo) == 1){
            panelFoguete.setVisible(true);
            btnCadastrarFoguete.setVisible(false);
            foguete = dao.pesquisarFoguete(nomeGrupo);
            
            //System.out.println(foguete.getNome());
            
            txtNomeFoguete.setText(foguete.getNome());
            txtPesoFoguete.setText(Float.toString(foguete.getPeso()));
        } else {
            panelFoguete.setVisible(false);
        }
    }
    
    public void atualizarLancamentos(){
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeGrupo = new javax.swing.JLabel();
        lblTurma = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMembros = new javax.swing.JTable();
        btnAdicionarMembro = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelFoguete = new javax.swing.JPanel();
        btnRegistrarLancamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFoguete = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPesoFoguete = new javax.swing.JTextField();
        txtPesoFoguete1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCadastrarFoguete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNomeGrupo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNomeGrupo.setText("Nome do Grupo");

        lblTurma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTurma.setText("Turma");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Membros"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableMembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RM"
            }
        ));
        jScrollPane1.setViewportView(tableMembros);

        btnAdicionarMembro.setText("Adicionar Membro");
        btnAdicionarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMembroActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar Membro");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 301, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(btnAdicionarMembro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnDeletar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnAdicionarMembro, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .add(btnDeletar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelFoguete.setBorder(javax.swing.BorderFactory.createTitledBorder("Foguete"));
        panelFoguete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnRegistrarLancamento.setText("Registrar Lançamento");
        btnRegistrarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLancamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        txtNomeFoguete.setEditable(false);

        jLabel2.setText("Peso (kg)");

        txtPesoFoguete.setEditable(false);

        txtPesoFoguete1.setEditable(false);

        jLabel3.setText("Total de Lançamentos");

        jButton3.setText("Histórico");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelFogueteLayout = new org.jdesktop.layout.GroupLayout(panelFoguete);
        panelFoguete.setLayout(panelFogueteLayout);
        panelFogueteLayout.setHorizontalGroup(
            panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelFogueteLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelFogueteLayout.createSequentialGroup()
                        .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtPesoFoguete)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtNomeFoguete)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtPesoFoguete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(panelFogueteLayout.createSequentialGroup()
                        .add(btnEditar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnRegistrarLancamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFogueteLayout.setVerticalGroup(
            panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelFogueteLayout.createSequentialGroup()
                .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelFogueteLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(txtNomeFoguete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtPesoFoguete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtPesoFoguete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 184, Short.MAX_VALUE)
                .add(panelFogueteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnEditar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnRegistrarLancamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCadastrarFoguete.setText("Cadastrar Foguete");
        btnCadastrarFoguete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFogueteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator1)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(panelFoguete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblTurma)
                            .add(lblNomeGrupo))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnCadastrarFoguete)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lblNomeGrupo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblTurma))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, btnCadastrarFoguete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panelFoguete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCadastrarFogueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFogueteActionPerformed
        JTextField txtNome = new JTextField();
        JTextField txtPeso = new JTextField();
        String nomeGrupo = lblNomeGrupo.getText();

        Object[] message = {
            "Nome do Foguete", txtNome,
            "Peso do Foguete", txtPeso,

        };
        int option = JOptionPane.showConfirmDialog(this, message, "Preencha os Campos", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION){
            String nome = txtNome.getText();
            float peso = Float.parseFloat(txtPeso.getText());
            
            Foguete foguete = new Foguete(nome, peso, nomeGrupo);
            
        
            if(dao.registrarFoguete(foguete, nomeGrupo)){
                preencherFoguete();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar Foguete");
            }
        }
    }//GEN-LAST:event_btnCadastrarFogueteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void btnRegistrarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLancamentoActionPerformed
        JTextField txtdistancia = new JTextField();
        JTextField txtangulo = new JTextField();
        JTextField txtvelocidade_vento = new JTextField();
        JTextField txtaltitude_maxima = new JTextField();
        JTextField txtvelocidade_maxima = new JTextField();
        JTextField txtpico_acelaracao = new JTextField();
        JTextField txtaceleracao_media = new JTextField();
        JTextField txttempo_apogeu_descida = new JTextField();
        JTextField txtaltitude_ejecao = new JTextField();
        JTextField txttaxa_descida = new JTextField();
        JTextField txtduracao = new JTextField();
        String grupo = lblNomeGrupo.getText();

        Object[] message = {
            "distancia", txtdistancia,
            "angulo", txtangulo,
            "velocidade_vento", txtvelocidade_vento,
            "altitude_maxima", txtaltitude_maxima,
            "velocidade_maxima", txtvelocidade_maxima,
            "pico_acelaracao", txtpico_acelaracao,
            "aceleracao_media", txtaceleracao_media,
            "tempo_apogeu_descida", txttempo_apogeu_descida,
            "altitude_ejecao", txtaltitude_ejecao,
            "taxa_descida", txttaxa_descida,
            "duracao", txtduracao,
        };
        int option = JOptionPane.showConfirmDialog(this, message, "Registrar Lançamento", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (option == JOptionPane.OK_OPTION){
            float distancia = Float.parseFloat(txtdistancia.getText());
            float angulo = Float.parseFloat(txtangulo.getText());
            float velocidade_vento = Float.parseFloat(txtvelocidade_vento.getText());
            float altitude_maxima = Float.parseFloat(txtaltitude_maxima.getText());
            float velocidade_maxima = Float.parseFloat(txtvelocidade_maxima.getText());
            float pico_aceleracao = Float.parseFloat(txtpico_acelaracao.getText());
            float aceleracao_media = Float.parseFloat(txtaceleracao_media.getText());
            float tempo_apogeu_descida = Float.parseFloat(txttempo_apogeu_descida.getText());
            float altitude_ejecao = Float.parseFloat(txtaltitude_ejecao.getText());
            float taxa_descida = Float.parseFloat(txttaxa_descida.getText());
            float duracao = Float.parseFloat(txtduracao.getText());
            int id_grupo = 0;
            
            Lancamento lancamento = new Lancamento(id_grupo, distancia, angulo, velocidade_vento, altitude_maxima, velocidade_maxima, pico_aceleracao, aceleracao_media, tempo_apogeu_descida, altitude_ejecao, altitude_ejecao, taxa_descida, duracao);
            
            if(dao.registrarLancamento(lancamento)){
                JOptionPane.showMessageDialog(this, "Lançamento Registrado");
            }
            
        }
    }//GEN-LAST:event_btnRegistrarLancamentoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int rm = Integer.parseInt(JOptionPane.showInputDialog("Insira o RM do Aluno"));
        
        if(dao.deletarAluno(rm)){
            JOptionPane.showMessageDialog(this, "Aluno Deletado");
            preencherTabela(lblNomeGrupo.getText());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAdicionarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMembroActionPerformed
        JTextField txtNome = new JTextField();
        JTextField txtRM = new JTextField();
        String grupo = lblNomeGrupo.getText();

        Object[] message = {
            "Nome", txtNome,
            "RM", txtRM,

        };
        int option = JOptionPane.showConfirmDialog(this, message, "Preencha os Campos", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION){
            String nome = txtNome.getText();
            int rm = Integer.parseInt(txtRM.getText());
            
            if(txtNome.getText().isEmpty() || txtRM.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Preencha Todos os campos");
            } else {
                Aluno aluno = new Aluno(rm, nome, grupo);
        
                if(dao.registrarAluno(aluno)){
                    preencherTabela(grupo);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir Aluno");
                }
            }
        }
    }//GEN-LAST:event_btnAdicionarMembroActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        JTextField txtNome = new JTextField();
        JTextField txtPeso = new JTextField();
        String nomeGrupo = lblNomeGrupo.getText();
        
        txtPeso.setText(txtPesoFoguete.getText());
        txtNome.setText(txtNomeFoguete.getText());

        Object[] message = {
            "Nome do Foguete", txtNome,
            "Peso do Foguete", txtPeso,

        };
        int option = JOptionPane.showConfirmDialog(this, message, "Preencha os Campos", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION){
            String nome = txtNome.getText();
            float peso = Float.parseFloat(txtPeso.getText());
            
            Foguete foguete = new Foguete(nome, peso, nomeGrupo);
        
            if(dao.editarFoguete(foguete)){
                preencherFoguete();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar Foguete");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            // select Look and Feel
            //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");  
            //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");    
            //UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");  
            //UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");  
            //UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel"); 

            // start application
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelGrupoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarMembro;
    private javax.swing.JButton btnCadastrarFoguete;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegistrarLancamento;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNomeGrupo;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JPanel panelFoguete;
    private javax.swing.JTable tableMembros;
    private javax.swing.JTextField txtNomeFoguete;
    private javax.swing.JTextField txtPesoFoguete;
    private javax.swing.JTextField txtPesoFoguete1;
    // End of variables declaration//GEN-END:variables

}
